# Generated by Django 5.1.7 on 2025-04-01 01:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('counterparty_type', models.CharField(choices=[('BANK', 'Bank'), ('BROKER', 'Broker'), ('EXCHANGE', 'Exchange'), ('CLEARING_HOUSE', 'Clearing House'), ('INVESTMENT_FIRM', 'Investment Firm'), ('OTHER', 'Other')], max_length=20)),
                ('credit_rating', models.CharField(choices=[('AAA', 'AAA'), ('AA+', 'AA+'), ('AA', 'AA'), ('AA-', 'AA-'), ('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('BBB+', 'BBB+'), ('BBB', 'BBB'), ('BBB-', 'BBB-'), ('NR', 'Not Rated')], default='NR', max_length=5)),
                ('legal_entity_identifier', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('risk_score', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Counterparties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquityPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], default='OPEN', max_length=10)),
                ('position_type', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('trade_date', models.DateTimeField()),
                ('company_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='thinkorswim.counterparty')),
            ],
        ),
    ]
